filters = {
    'jazz':r'john coltrane|miles davis|eric dolphy|keith jarrett|billie holiday|nina simone|louis armstrong|fela kuti|charles mingus|sun ra|mahavishnu orchestra|fela kuti',
    'xmas':r'christmas|xmas|fairytale of new york|winter dreams|reindeer|messiah|paul robeson|arthur tracy|john mccormack',
    'elephant6':r'gold bears|always red society|neutral milk hotel|olivia tremor|music tapes|julian koster|apples in stereo|major organ|circulatory system|beulah|jaff mangum|gerbils|hawk and a hacksaw|black swan network|elf power|the instruments|little fyodore|nesey gallons|von hemmling',
    'irish':r'pogues|dubliners|planxty|parting glass|clancy brothers|liam clancy|john mccormack',
    'balkan':r'a hawk and a hacksaw|orange twin field works|london bulgarian choir|music of bulgaria',
    'psc':r'legavrik|budweiser combination|noise engine|hypnic jerk|comaphoria|hen|mas|the bolt|katzenklavier',
    'seenlive':r'legavrik|london bulgarian choir|dear landlord|hawk and a hacksaw|chesney hawkes|gypsy hill|wurzels|joanna newson|music tapes|thurston moore|sonic youth|minutemen|the fall|apples in stereo|yann tiersen|magic band|olivia tremor conrtol|rafael toral|magnetic fields|jeff mangum|sebadoh|beirut|mf doom|madlib|madvillain|godspeed you|frank turner|pogues|dick gaughan|my bloody valentine|de la soul|phosphorescent|camper van beethoven|eaux|cat power|dylan carlson|television|lee ranaldo|scritti politti|manic street preachers|laetitia sadier|stereolab|neutral milk hotel|arcade fire|dexys',
    'hiphop':r'beastie boys|dj danger mouse|jay(-| )z|eric b|gang starr|goldie lookin|gorillaz|madvillain|mf doom|viktor vaughn|king geedorah|jj doom|dangerdoom|madlib|n\.w\.a|nas|notorious b\.i\.g|dirty bastard|outkast|dilla|public enemy|streets|de la soul|wu-tang|gza|rza|ghostface|k\.?m\.?d\.?|tribe called quest|mobb deep|jeru the damaja|roots|run(-| )d\.?m\.?c\.?|kendrick lamar|mos def|skitz|nehru|dr. octagon|cannibal ox',
    'work':r'late music|boards of canada|john coltrane|godspeed you|sonatas and interludes|eric dolphy|keith jarrett|miles davis|charles mingus|hypnic jerk|explanation ii|varese|bach|helen o.?hara|underworld|metamophic reproduction miracle|mahavishnu orchestra|fela kuti|mike oldfield|dj shadow|the mix.up|special herbs|hala strana|neu!|kraftwerk|morricone',
    'twis':r'godspeed you|explanation ii|ambient works|natural snow buildings|ohia|portishead|stereolab|varese|sigur ros'
  }
